# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'soil_moisture_dialog_base.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_SoilMoistureDialogBase(object):
    def setupUi(self, SoilMoistureDialogBase):
        if not SoilMoistureDialogBase.objectName():
            SoilMoistureDialogBase.setObjectName(u"SoilMoistureDialogBase")
        SoilMoistureDialogBase.resize(544, 481)
        self.tabWidget = QTabWidget(SoilMoistureDialogBase)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(20, 20, 511, 441))
        font = QFont()
        font.setFamily(u"Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.OTinput = QWidget()
        self.OTinput.setObjectName(u"OTinput")
        self.tb_otinput = QTextBrowser(self.OTinput)
        self.tb_otinput.setObjectName(u"tb_otinput")
        self.tb_otinput.setGeometry(QRect(209, 12, 281, 351))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.tb_otinput.setFont(font1)
        self.cb_clip_bands = QCheckBox(self.OTinput)
        self.cb_clip_bands.setObjectName(u"cb_clip_bands")
        self.cb_clip_bands.setGeometry(QRect(10, 130, 111, 19))
        font2 = QFont()
        font2.setFamily(u"Times New Roman")
        font2.setPointSize(11)
        self.cb_clip_bands.setFont(font2)
        self.pb_ot_compute = QPushButton(self.OTinput)
        self.pb_ot_compute.setObjectName(u"pb_ot_compute")
        self.pb_ot_compute.setGeometry(QRect(100, 380, 181, 24))
        font3 = QFont()
        font3.setBold(False)
        font3.setWeight(50)
        self.pb_ot_compute.setFont(font3)
        self.pb_ot_close = QPushButton(self.OTinput)
        self.pb_ot_close.setObjectName(u"pb_ot_close")
        self.pb_ot_close.setGeometry(QRect(300, 380, 75, 24))
        self.pb_ot_close.setFont(font3)
        self.label = QLabel(self.OTinput)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 81, 16))
        self.label_2 = QLabel(self.OTinput)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 71, 16))
        self.label_3 = QLabel(self.OTinput)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 60, 47, 41))
        self.label_4 = QLabel(self.OTinput)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 100, 71, 21))
        self.cb_save_red = QCheckBox(self.OTinput)
        self.cb_save_red.setObjectName(u"cb_save_red")
        self.cb_save_red.setGeometry(QRect(10, 200, 131, 17))
        self.cb_save_nir = QCheckBox(self.OTinput)
        self.cb_save_nir.setObjectName(u"cb_save_nir")
        self.cb_save_nir.setGeometry(QRect(10, 230, 141, 17))
        self.cb_save_lst = QCheckBox(self.OTinput)
        self.cb_save_lst.setObjectName(u"cb_save_lst")
        self.cb_save_lst.setGeometry(QRect(10, 260, 141, 17))
        self.cb_save_intermediate = QCheckBox(self.OTinput)
        self.cb_save_intermediate.setObjectName(u"cb_save_intermediate")
        self.cb_save_intermediate.setGeometry(QRect(10, 290, 181, 17))
        self.pb_red = QPushButton(self.OTinput)
        self.pb_red.setObjectName(u"pb_red")
        self.pb_red.setGeometry(QRect(100, 10, 75, 23))
        font4 = QFont()
        font4.setBold(False)
        font4.setItalic(False)
        font4.setUnderline(False)
        font4.setWeight(50)
        self.pb_red.setFont(font4)
        self.pb_nir = QPushButton(self.OTinput)
        self.pb_nir.setObjectName(u"pb_nir")
        self.pb_nir.setGeometry(QRect(100, 40, 75, 23))
        self.pb_nir.setFont(font4)
        self.pb_shape = QPushButton(self.OTinput)
        self.pb_shape.setObjectName(u"pb_shape")
        self.pb_shape.setGeometry(QRect(100, 100, 75, 23))
        self.pb_shape.setFont(font4)
        self.pb_lst = QPushButton(self.OTinput)
        self.pb_lst.setObjectName(u"pb_lst")
        self.pb_lst.setGeometry(QRect(100, 70, 75, 23))
        self.pb_lst.setFont(font4)
        self.label_11 = QLabel(self.OTinput)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 170, 111, 21))
        self.tabWidget.addTab(self.OTinput, "")
        self.SMinput = QWidget()
        self.SMinput.setObjectName(u"SMinput")
        self.le_lat_min = QLineEdit(self.SMinput)
        self.le_lat_min.setObjectName(u"le_lat_min")
        self.le_lat_min.setGeometry(QRect(90, 100, 51, 22))
        self.le_lat_max = QLineEdit(self.SMinput)
        self.le_lat_max.setObjectName(u"le_lat_max")
        self.le_lat_max.setGeometry(QRect(150, 100, 51, 22))
        self.le_long_min = QLineEdit(self.SMinput)
        self.le_long_min.setObjectName(u"le_long_min")
        self.le_long_min.setGeometry(QRect(90, 130, 51, 22))
        self.le_long_max = QLineEdit(self.SMinput)
        self.le_long_max.setObjectName(u"le_long_max")
        self.le_long_max.setGeometry(QRect(150, 130, 51, 22))
        self.pb_sm_extract = QPushButton(self.SMinput)
        self.pb_sm_extract.setObjectName(u"pb_sm_extract")
        self.pb_sm_extract.setGeometry(QRect(10, 180, 181, 24))
        self.pb_sm_extract.setFont(font3)
        self.pb_sm_close = QPushButton(self.SMinput)
        self.pb_sm_close.setObjectName(u"pb_sm_close")
        self.pb_sm_close.setGeometry(QRect(300, 380, 75, 24))
        self.pb_sm_close.setFont(font3)
        self.pb_sm_compute = QPushButton(self.SMinput)
        self.pb_sm_compute.setObjectName(u"pb_sm_compute")
        self.pb_sm_compute.setGeometry(QRect(110, 380, 171, 24))
        self.pb_sm_compute.setFont(font3)
        self.tb_sminput = QTextBrowser(self.SMinput)
        self.tb_sminput.setObjectName(u"tb_sminput")
        self.tb_sminput.setGeometry(QRect(210, 10, 281, 351))
        self.tb_sminput.setFont(font1)
        self.label_5 = QLabel(self.SMinput)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 121, 20))
        self.label_6 = QLabel(self.SMinput)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 60, 201, 16))
        self.label_7 = QLabel(self.SMinput)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 100, 61, 16))
        self.label_8 = QLabel(self.SMinput)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 130, 71, 21))
        self.label_9 = QLabel(self.SMinput)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(90, 80, 47, 13))
        self.label_10 = QLabel(self.SMinput)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(150, 80, 47, 13))
        self.pb_sm = QPushButton(self.SMinput)
        self.pb_sm.setObjectName(u"pb_sm")
        self.pb_sm.setGeometry(QRect(130, 20, 75, 23))
        self.pb_sm.setFont(font3)
        self.tabWidget.addTab(self.SMinput, "")

        self.retranslateUi(SoilMoistureDialogBase)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(SoilMoistureDialogBase)
    # setupUi

    def retranslateUi(self, SoilMoistureDialogBase):
        SoilMoistureDialogBase.setWindowTitle(QCoreApplication.translate("SoilMoistureDialogBase", u"SMC", None))
        self.cb_clip_bands.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Clip bands", None))
        self.pb_ot_compute.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Compute all parameters", None))
        self.pb_ot_close.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Close", None))
        self.label.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Red band", None))
        self.label_2.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"NIR band", None))
        self.label_3.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"LST", None))
        self.label_4.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Shape file", None))
        self.cb_save_red.setText(QCoreApplication.translate("SoilMoistureDialogBase", u" Red band", None))
        self.cb_save_nir.setText(QCoreApplication.translate("SoilMoistureDialogBase", u" NIR  band", None))
        self.cb_save_lst.setText(QCoreApplication.translate("SoilMoistureDialogBase", u" LST band", None))
        self.cb_save_intermediate.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Intermediate parameters", None))
        self.pb_red.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Browse", None))
        self.pb_nir.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Browse", None))
        self.pb_shape.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Browse", None))
        self.pb_lst.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Browse", None))
        self.label_11.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Saving options", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OTinput), QCoreApplication.translate("SoilMoistureDialogBase", u"O/T input", None))
        self.pb_sm_extract.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Extract for location (LR)", None))
        self.pb_sm_close.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Close", None))
        self.pb_sm_compute.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Compute soil moisture", None))
        self.label_5.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"SM product", None))
        self.label_6.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Enter extent", None))
        self.label_7.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Latitude", None))
        self.label_8.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Longitude", None))
        self.label_9.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Min", None))
        self.label_10.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Max", None))
        self.pb_sm.setText(QCoreApplication.translate("SoilMoistureDialogBase", u"Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SMinput), QCoreApplication.translate("SoilMoistureDialogBase", u"SM input", None))
    # retranslateUi

